"""HydeEmbedder — drop-in Embedder wrapper that applies HyDE rewriting.

Wraps any :class:`Embedder` so that, at embed time:
  - The query text is augmented or replaced by a hypothetical-answer
    rewrite generated by a local LLM (see ``orchestration.sdp.hyde``).
  - The underlying embedder then produces a vector over the augmented text.

By default uses **fuse mode**: ``"<original question> <hypothetical answer>"``.
This way the embedding sees the original wording *plus* answer-style
wording. Pure replace mode is also supported (set ``mode="replace"``).

When the LLM client is unreachable, HyDE silently returns the original
query text unchanged — embedding still happens, just without the rewrite.
"""
from orchestration.embedder.base import Embedder
from orchestration.pipeline.contracts import Classification, EmbeddedQuery, Query
from orchestration.sam._ollama_client import OllamaClient
from orchestration.sdp.hyde import hyde_fuse, hyde_multi_rewrite, hyde_rewrite


class HydeEmbedder(Embedder):
    """Wraps an Embedder; rewrites query text via HyDE before embedding.

    Modes (Phase B3 + Phase C9):
      ``fuse``     — concat original + one hypothetical answer (B3, default)
      ``replace``  — embed the hypothetical answer alone
      ``multi``    — concat original + N hypothetical answers across styles
                     (C9 — best for paraphrase-heavy retrieval)
    """

    def __init__(
        self,
        base: Embedder,
        llm_client: OllamaClient | None,
        mode: str = "fuse",
        n_paraphrases: int = 3,
    ) -> None:
        if mode not in {"fuse", "replace", "multi"}:
            raise ValueError(f"mode must be 'fuse', 'replace', or 'multi'; got {mode!r}")
        self.base = base
        self.llm_client = llm_client
        self.mode = mode
        self.n_paraphrases = n_paraphrases

    @property
    def version(self) -> str:
        if self.mode == "multi":
            return f"{self.base.version}+hyde-multi-{self.n_paraphrases}"
        return f"{self.base.version}+hyde-{self.mode}"

    async def embed(
        self, query: Query, classification: Classification
    ) -> EmbeddedQuery:
        if self.llm_client is None:
            return await self.base.embed(query, classification)

        if self.mode == "fuse":
            new_text = await hyde_fuse(query.text, self.llm_client)
        elif self.mode == "multi":
            # C9: multi-paraphrase. Generate up to n stylistically diverse
            # hypothetical answers in parallel; concat with the original.
            parts = await hyde_multi_rewrite(
                query.text, self.llm_client, n=self.n_paraphrases,
            )
            new_text = " ".join(parts) if len(parts) > 1 else query.text
        else:  # replace
            new_text = await hyde_rewrite(query.text, self.llm_client)

        if new_text == query.text:
            return await self.base.embed(query, classification)

        modified = query.model_copy(update={"text": new_text})
        embedded = await self.base.embed(modified, classification)
        # Preserve the ORIGINAL query in the returned EmbeddedQuery so the
        # rest of the pipeline (BM25, trace logs) sees the user's wording.
        return embedded.model_copy(update={"query": query})
