-- =========================================================================
--  GML — single consolidated migration (001 + 002 + 003 + 004 + 005 + 006 + 007 + 008)
--
--  Apply this once on a fresh Postgres 16 + pgvector database:
--
--      psql "$GML_DATABASE_URL" -f migrations/all_in_one.sql
--
--  Everything is idempotent (CREATE … IF NOT EXISTS, ON CONFLICT DO NOTHING,
--  DROP POLICY IF EXISTS, etc.) — safe to re-run on a partially-migrated DB.
--
--  Prereqs (covered by deploy/gcp/02-install-postgres.sh):
--    * Postgres 16
--    * pgvector ≥ 0.8 installed at the cluster level
--    * pg_trgm + pgcrypto available (ship with Postgres)
--    * a ``gml_app`` role + ``gml`` database already created
--
--  The granular per-step files in this directory (001_*.sql … 008_*.sql) are
--  the source of truth — this file is generated by concatenating them in
--  order. If you edit anything, update the per-step file FIRST then rebuild
--  this file (cat 00*.sql > all_in_one.sql) so they stay in sync.
-- =========================================================================

BEGIN;

-- -----------------------------------------------------------------------
-- 001  EXTENSIONS
-- -----------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS vector;     -- pgvector — dense retrieval
CREATE EXTENSION IF NOT EXISTS pg_trgm;    -- substring similarity
CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid()

CREATE TABLE IF NOT EXISTS schema_migrations (
    filename    TEXT PRIMARY KEY,
    applied_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    checksum    TEXT
);

-- -----------------------------------------------------------------------
-- 002  USERS  +  USER_KEYS
-- -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    user_id          TEXT        PRIMARY KEY,
    email            TEXT        UNIQUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    plan             TEXT        NOT NULL DEFAULT 'free'
                                 CHECK (plan IN ('free', 'pro', 'team', 'admin')),
    quota_bytes      BIGINT      NOT NULL DEFAULT 1073741824,  -- 1 GiB
    bytes_used       BIGINT      NOT NULL DEFAULT 0,
    warned_at_90pct  BOOLEAN     NOT NULL DEFAULT FALSE,
    is_active        BOOLEAN     NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS user_keys (
    key            TEXT        PRIMARY KEY,
    user_id        TEXT        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    label          TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at   TIMESTAMPTZ,
    is_active      BOOLEAN     NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS user_keys_user_id_idx ON user_keys(user_id);
CREATE INDEX IF NOT EXISTS user_keys_active_idx  ON user_keys(is_active) WHERE is_active;

-- -----------------------------------------------------------------------
-- 003  MEMORIES  +  non-FTS indexes
-- -----------------------------------------------------------------------
-- Vector dim is locked to 384 (bge-small-en-v1.5). To swap to bge-large
-- (1024) later: ALTER TABLE memories DROP COLUMN embedding, ADD COLUMN
-- embedding vector(1024); + rebuild the HNSW index.
CREATE TABLE IF NOT EXISTS memories (
    id               TEXT        PRIMARY KEY,
    user_id          TEXT        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    content          TEXT        NOT NULL,
    entity           TEXT,
    attribute        TEXT,
    value            TEXT,
    source           TEXT        NOT NULL DEFAULT 'conversation',
    authority_score  REAL        NOT NULL DEFAULT 0.7,
    pinned           BOOLEAN     NOT NULL DEFAULT FALSE,
    "timestamp"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    raw_metadata     JSONB,
    summary_short    TEXT,
    embedding        vector(384),
    byte_size        INTEGER     NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS memories_user_id_idx       ON memories(user_id);
CREATE INDEX IF NOT EXISTS memories_user_entity_idx   ON memories(user_id, entity) WHERE entity IS NOT NULL;
CREATE INDEX IF NOT EXISTS memories_user_time_idx     ON memories(user_id, "timestamp" DESC);
CREATE INDEX IF NOT EXISTS memories_content_trgm_idx  ON memories USING GIN (content gin_trgm_ops);
CREATE INDEX IF NOT EXISTS memories_embedding_hnsw_idx
    ON memories USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- -----------------------------------------------------------------------
-- 004  BYTE-TRACKING TRIGGER  (auto-maintains users.bytes_used)
-- -----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION _gml_update_bytes_used()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE users SET bytes_used = bytes_used + NEW.byte_size
            WHERE user_id = NEW.user_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE users SET bytes_used = GREATEST(0, bytes_used - OLD.byte_size)
            WHERE user_id = OLD.user_id;
    ELSIF TG_OP = 'UPDATE' THEN
        IF NEW.user_id = OLD.user_id THEN
            UPDATE users SET bytes_used = bytes_used + NEW.byte_size - OLD.byte_size
                WHERE user_id = NEW.user_id;
        ELSE
            UPDATE users SET bytes_used = GREATEST(0, bytes_used - OLD.byte_size)
                WHERE user_id = OLD.user_id;
            UPDATE users SET bytes_used = bytes_used + NEW.byte_size
                WHERE user_id = NEW.user_id;
        END IF;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS memories_bytes_used ON memories;
CREATE TRIGGER memories_bytes_used
    AFTER INSERT OR UPDATE OR DELETE ON memories
    FOR EACH ROW
    EXECUTE FUNCTION _gml_update_bytes_used();

-- -----------------------------------------------------------------------
-- 005  ROW-LEVEL SECURITY  (per-tenant isolation)
-- -----------------------------------------------------------------------
-- The application sets app.current_user_id on every request. RLS then
-- restricts SELECT/UPDATE/DELETE on memories + user_keys to rows owned by
-- that user. Setting app.is_admin = 'true' bypasses (admin endpoints).
ALTER TABLE memories  ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_keys ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS memories_self ON memories;
CREATE POLICY memories_self ON memories
    USING (
        user_id = current_setting('app.current_user_id', TRUE)
        OR current_setting('app.is_admin', TRUE) = 'true'
    );

DROP POLICY IF EXISTS user_keys_self ON user_keys;
CREATE POLICY user_keys_self ON user_keys
    USING (
        user_id = current_setting('app.current_user_id', TRUE)
        OR current_setting('app.is_admin', TRUE) = 'true'
    );

GRANT USAGE ON SCHEMA public TO gml_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO gml_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO gml_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO gml_app;

-- -----------------------------------------------------------------------
-- 006  FTS  (tsvector for BM25-style sparse retrieval)
-- -----------------------------------------------------------------------
ALTER TABLE memories
    ADD COLUMN IF NOT EXISTS content_tsv tsvector
    GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(content,   '')), 'A')
        || setweight(to_tsvector('english', coalesce(entity,    '')), 'B')
        || setweight(to_tsvector('english', coalesce(value,     '')), 'B')
        || setweight(to_tsvector('english', coalesce(attribute, '')), 'C')
    ) STORED;

CREATE INDEX IF NOT EXISTS memories_content_tsv_idx
    ON memories USING GIN (content_tsv);

COMMENT ON COLUMN memories.content_tsv IS
    'Full-text vector for BM25-style sparse retrieval. Weighted: content=A, entity+value=B, attribute=C. Query via ts_rank_cd(content_tsv, plainto_tsquery(''english'', $q)).';

-- -----------------------------------------------------------------------
-- 007  CONVENIENCE VIEW  (powers /api/me/quota)
-- -----------------------------------------------------------------------
CREATE OR REPLACE VIEW user_quota_status AS
SELECT
    u.user_id,
    u.plan,
    u.quota_bytes,
    u.bytes_used,
    CASE
        WHEN u.quota_bytes = 0 THEN 0.0
        ELSE LEAST(1.0, u.bytes_used::float / u.quota_bytes::float)
    END AS pct_used,
    u.warned_at_90pct,
    (SELECT count(*) FROM memories m WHERE m.user_id = u.user_id) AS memory_count
FROM users u;

GRANT SELECT ON user_quota_status TO gml_app;

-- -----------------------------------------------------------------------
-- 008  AAL COLUMNS  (canonical {simplemem, sjson} per row)
-- -----------------------------------------------------------------------
ALTER TABLE memories
    ADD COLUMN IF NOT EXISTS aal_simplemem TEXT,
    ADD COLUMN IF NOT EXISTS aal_sjson JSONB;

CREATE INDEX IF NOT EXISTS memories_aal_sjson_idx
    ON memories USING GIN (aal_sjson jsonb_path_ops);

CREATE INDEX IF NOT EXISTS memories_aal_subject_idx
    ON memories ((aal_sjson ->> 'subject'))
    WHERE aal_sjson IS NOT NULL;

COMMENT ON COLUMN memories.aal_simplemem IS
    'Canonical AAL view: one-line natural sentence. Mirrors content for AAL-written rows.';
COMMENT ON COLUMN memories.aal_sjson IS
    'Canonical AAL view: structured triple {subject, verb, object, time, negated, confidence, category, ...}. NULL for legacy rows.';

-- -----------------------------------------------------------------------
-- 009  USER PASSWORDS (email + password auth → JWT)
-- -----------------------------------------------------------------------
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS password_hash TEXT;
COMMENT ON COLUMN users.password_hash IS
    'pbkdf2_sha256$iterations$salt_b64$hash_b64 — set by email+password signup; NULL for key-only users.';

-- -----------------------------------------------------------------------
-- BOOKKEEPING
-- -----------------------------------------------------------------------
-- Record each step in schema_migrations so apply_all.sh treats the DB as
-- fully migrated and doesn't re-run the per-step files.
INSERT INTO schema_migrations (filename, applied_at) VALUES
    ('001_extensions.sql',           now()),
    ('002_users_and_keys.sql',       now()),
    ('003_memories.sql',             now()),
    ('004_byte_tracking.sql',        now()),
    ('005_row_level_security.sql',   now()),
    ('006_fts.sql',                  now()),
    ('007_views.sql',                now()),
    ('008_aal_columns.sql',          now()),
    ('009_user_passwords.sql',       now())
ON CONFLICT (filename) DO NOTHING;

COMMIT;

-- =========================================================================
-- Post-apply sanity check (read-only, safe to run repeatedly):
--
--   SELECT filename, applied_at FROM schema_migrations ORDER BY applied_at;
--   SELECT count(*) FROM pg_indexes WHERE tablename='memories';
--   SELECT relname, n_live_tup FROM pg_stat_user_tables WHERE schemaname='public';
-- =========================================================================
